<?php

namespace ContainerHxT1nTr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SshZmLBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SshZmLB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SshZmLB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'counRepo' => ['privates', 'App\\Repository\\CountryRepository', 'getCountryRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ser' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'counRepo' => 'App\\Repository\\CountryRepository',
            'em' => '?',
            'ser' => '?',
        ]);
    }
}
