<?php

namespace ContainerHxT1nTr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bh93XTZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bh93XTZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bh93XTZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'residentRepo' => ['privates', 'App\\Repository\\ResidentRepository', 'getResidentRepositoryService', true],
        ], [
            'em' => '?',
            'residentRepo' => 'App\\Repository\\ResidentRepository',
        ]);
    }
}
