<?php

namespace ContainerHxT1nTr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FzeNZQkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fzeNZQk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fzeNZQk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CityController::create' => ['privates', '.service_locator.SshZmLB', 'get_ServiceLocator_SshZmLBService', true],
            'App\\Controller\\CityController::delete' => ['privates', '.service_locator..op60cN', 'get_ServiceLocator__Op60cNService', true],
            'App\\Controller\\CityController::index' => ['privates', '.service_locator.vh3.zYg', 'get_ServiceLocator_Vh3_ZYgService', true],
            'App\\Controller\\CityController::update' => ['privates', '.service_locator.3dEuDiH', 'get_ServiceLocator_3dEuDiHService', true],
            'App\\Controller\\CountryController::create' => ['privates', '.service_locator.33nL76K', 'get_ServiceLocator_33nL76KService', true],
            'App\\Controller\\CountryController::delete' => ['privates', '.service_locator.iQ.3lyH', 'get_ServiceLocator_IQ_3lyHService', true],
            'App\\Controller\\CountryController::index' => ['privates', '.service_locator.lvI1Mgl', 'get_ServiceLocator_LvI1MglService', true],
            'App\\Controller\\CountryController::update' => ['privates', '.service_locator.Rjhl3xT', 'get_ServiceLocator_Rjhl3xTService', true],
            'App\\Controller\\ResidentController::avgResidentAgeOf' => ['privates', '.service_locator.J9yijQX', 'get_ServiceLocator_J9yijQXService', true],
            'App\\Controller\\ResidentController::create' => ['privates', '.service_locator.Hv3eEHJ', 'get_ServiceLocator_Hv3eEHJService', true],
            'App\\Controller\\ResidentController::delete' => ['privates', '.service_locator.Bh93XTZ', 'get_ServiceLocator_Bh93XTZService', true],
            'App\\Controller\\ResidentController::index' => ['privates', '.service_locator.jy3Ew9t', 'get_ServiceLocator_Jy3Ew9tService', true],
            'App\\Controller\\ResidentController::update' => ['privates', '.service_locator.qM3GVto', 'get_ServiceLocator_QM3GVtoService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CityController:create' => ['privates', '.service_locator.SshZmLB', 'get_ServiceLocator_SshZmLBService', true],
            'App\\Controller\\CityController:delete' => ['privates', '.service_locator..op60cN', 'get_ServiceLocator__Op60cNService', true],
            'App\\Controller\\CityController:index' => ['privates', '.service_locator.vh3.zYg', 'get_ServiceLocator_Vh3_ZYgService', true],
            'App\\Controller\\CityController:update' => ['privates', '.service_locator.3dEuDiH', 'get_ServiceLocator_3dEuDiHService', true],
            'App\\Controller\\CountryController:create' => ['privates', '.service_locator.33nL76K', 'get_ServiceLocator_33nL76KService', true],
            'App\\Controller\\CountryController:delete' => ['privates', '.service_locator.iQ.3lyH', 'get_ServiceLocator_IQ_3lyHService', true],
            'App\\Controller\\CountryController:index' => ['privates', '.service_locator.lvI1Mgl', 'get_ServiceLocator_LvI1MglService', true],
            'App\\Controller\\CountryController:update' => ['privates', '.service_locator.Rjhl3xT', 'get_ServiceLocator_Rjhl3xTService', true],
            'App\\Controller\\ResidentController:avgResidentAgeOf' => ['privates', '.service_locator.J9yijQX', 'get_ServiceLocator_J9yijQXService', true],
            'App\\Controller\\ResidentController:create' => ['privates', '.service_locator.Hv3eEHJ', 'get_ServiceLocator_Hv3eEHJService', true],
            'App\\Controller\\ResidentController:delete' => ['privates', '.service_locator.Bh93XTZ', 'get_ServiceLocator_Bh93XTZService', true],
            'App\\Controller\\ResidentController:index' => ['privates', '.service_locator.jy3Ew9t', 'get_ServiceLocator_Jy3Ew9tService', true],
            'App\\Controller\\ResidentController:update' => ['privates', '.service_locator.qM3GVto', 'get_ServiceLocator_QM3GVtoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CityController::create' => '?',
            'App\\Controller\\CityController::delete' => '?',
            'App\\Controller\\CityController::index' => '?',
            'App\\Controller\\CityController::update' => '?',
            'App\\Controller\\CountryController::create' => '?',
            'App\\Controller\\CountryController::delete' => '?',
            'App\\Controller\\CountryController::index' => '?',
            'App\\Controller\\CountryController::update' => '?',
            'App\\Controller\\ResidentController::avgResidentAgeOf' => '?',
            'App\\Controller\\ResidentController::create' => '?',
            'App\\Controller\\ResidentController::delete' => '?',
            'App\\Controller\\ResidentController::index' => '?',
            'App\\Controller\\ResidentController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CityController:create' => '?',
            'App\\Controller\\CityController:delete' => '?',
            'App\\Controller\\CityController:index' => '?',
            'App\\Controller\\CityController:update' => '?',
            'App\\Controller\\CountryController:create' => '?',
            'App\\Controller\\CountryController:delete' => '?',
            'App\\Controller\\CountryController:index' => '?',
            'App\\Controller\\CountryController:update' => '?',
            'App\\Controller\\ResidentController:avgResidentAgeOf' => '?',
            'App\\Controller\\ResidentController:create' => '?',
            'App\\Controller\\ResidentController:delete' => '?',
            'App\\Controller\\ResidentController:index' => '?',
            'App\\Controller\\ResidentController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
