<?php

namespace ContainerHxT1nTr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rjhl3xTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rjhl3xT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rjhl3xT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'countryRepo' => ['privates', 'App\\Repository\\CountryRepository', 'getCountryRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'ser' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'countryRepo' => 'App\\Repository\\CountryRepository',
            'em' => '?',
            'ser' => '?',
        ]);
    }
}
