<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxT1nTr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxT1nTr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxT1nTr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxT1nTr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxT1nTr\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxT1nTr',
    'container.build_id' => '15360579',
    'container.build_time' => 1635161003,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxT1nTr');
