<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'city_read' => [[], ['_controller' => 'App\\Controller\\CityController::index'], [], [['text', '/city']], [], []],
    'city_create' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\CityController::create'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/city']], [], []],
    'city_update' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\CityController::update'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/city']], [], []],
    'city_delete' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\CityController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/city']], [], []],
    'country_read' => [[], ['_controller' => 'App\\Controller\\CountryController::index'], [], [['text', '/country']], [], []],
    'country_create' => [[], ['_controller' => 'App\\Controller\\CountryController::create'], [], [['text', '/country']], [], []],
    'country_update' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\CountryController::update'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/country']], [], []],
    'country_delete' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\CountryController::delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/country']], [], []],
    'resident_read' => [[], ['_controller' => 'App\\Controller\\ResidentController::index'], [], [['text', '/resident']], [], []],
    'resident_create' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\ResidentController::create'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/resident']], [], []],
    'resident_update' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\ResidentController::update'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/resident']], [], []],
    'resident_delete' => [['id'], ['id' => '0', '_controller' => 'App\\Controller\\ResidentController::avgResidentAgeOf'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/resident/avgCity']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
